eureka:
  client:
    service-url.defaultZone: http://localhost:3100/eureka/
management:
  security:
    enabled : false
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: qiche
    password: 123456