spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: archimedes
      laber: master
eureka:
  client:
    service-url.defaultZone: http://localhost:3100/eureka/
management:
  security:
    enabled : false